library(shiny)
library(shinydashboard)
library(tidyverse)
library(DT)
library(plotly)
library(ggplot2)
library(shinythemes)

# Change the limit for scientific notation
options(scipen=999)

#ent_group_list <- c("People", "Geo-political", "Organizations", "Sports")

trump <- readRDS('data/shiny_data/trump.rds')
obama <- readRDS('data/shiny_data/obama.rds')
boris <- readRDS('data/shiny_data/boris.rds')
pelosi <- readRDS('data/shiny_data/pelosi.rds')
fauci <- readRDS('data/shiny_data/fauci.rds')
spain <- readRDS('data/shiny_data/spain.rds')
nyc <- readRDS('data/shiny_data/nyc.rds')
china <- readRDS('data/shiny_data/china.rds')
eu <- readRDS('data/shiny_data/eu.rds')
italy <- readRDS('data/shiny_data/italy.rds')
usa <- readRDS('data/shiny_data/usa.rds')
whitehouse <- readRDS('data/shiny_data/whitehouse.rds')
cdc <- readRDS('data/shiny_data/cdc.rds')
congress <- readRDS('data/shiny_data/congress.rds')
nhs <- readRDS('data/shiny_data/nhs.rds')
who <- readRDS('data/shiny_data/who.rds')
baseball <- readRDS('data/shiny_data/mlb.rds')
hockey <- readRDS('data/shiny_data/nhl.rds')
basketball <- readRDS('data/shiny_data/nba.rds')
soccer <- readRDS('data/shiny_data/fifa.rds')
football <- readRDS('data/shiny_data/nfl.rds')
